### ISSUE TITLE
Can't detect phishing accounts

### ISSUE THREAD

**Issue by Matsui9979** [git-disl/BERT4ETH#4]
Hello,
I set the parameters as written in the readme, but could not detect phishing accounts. If you don't mind, can you give me some trained models, or examples.
Thank you.

**Comment by H0uzC** [comment]
Hello, 
Please allow me to ask you a question, I also prepare to reproduce the experimental process of the paper. Can you run the whole process (from gen_seq.py to run_phishing_detection.py) according to the README given by the author? Except for the issue you mentioned about not being able to detect phishing accounts.
Thanks.

**Comment by Bayi-Hu** [comment]
Hi,

I will check the code and parameters shortly, and provide some trained models or examples.

Thanks,
Sihao

**Comment by Bayi-Hu** [comment]
Hello,

I have reorganized the code and tested it. The code should be able to reproduce the results presented in the paper.

Thank you,
Sihao

**Comment by Bayi-Hu** [comment]
> Hello, I set the parameters as written in the readme, but could not detect phishing accounts. If you don't mind, can you give me some trained models, or examples. Thank you.

Since the model is quite huge and requires corresponding vocabulary, training and testing data, it is difficult to upload all the intermediate files. However, I uploaded the output embedding to the (https://drive.google.com/file/d/1mQgO1LalWhjeR064VhPRmkLl_ztSTroW/view?usp=sharing), you can unzip it under the directory of "Model/inter_data" and run the "run_phishing_detection.py" or "run_phishing_detection_dnn.py" to get the phishing account detection results on the account representations. Parameters are specified in the README or run.sh.
